language: ruby
rvm:
- 2.2
#- 2.1
#- 2.0
- 1.9.3
env:
- DOCKER_IMAGES=debian:7 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=debian:7 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=debian:7 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=debian:7 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=debian:7 ANSIBLE_VERSIONS=2.2.1.0
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=2.2.1.0
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=2.2.1.0
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=2.2.1.0
sudo: false
services:
- docker
script:
- wget -O- bit.ly/ansibletest | sh -x
after_failure:
- cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    on_success: change
    on_failure: change
    rooms:
    - secure: YeHxhFZDJ+0/+7tkXpkCOA2+UMcyKDdGArQPl48UPardT/7yjY7XEtczMFxlrRr34sl5nH6oNfmkP0tWgXYQev6mTmlCDjzGWCy9qt3yyQ7aw6SWxbKebaWJv2EFHKzABiw+rcsJNy3UUetFUSRsqZUDFqotoDkvIxpiDkctGJ0onj+V/TjqMrgIvTRfJTdsWg53mZaPQumBcqax963XW0hILOiZHxmcjUhqZCMKyWn7NxmRXuHvSH78zNLUfmz2FlIV2InGOiDL/7YgVMc0DWGKXH53AwKZXuL+w5UYt5jlMoOMqh5E9mXyDkIjelB55YbFJ/G8w70qklCAABvURrNgzUi8bbFYspWtfN5mXg3B3b9vRIshiMMpkQgktiv/SrwYPz/y8S+1TL2LPB8uDdB4F0wfcXkDfIPtSI3gGv+u+iLriFv2BCA9tk9Mbd/6PeMHjHO1EY66t+mSO89BcfFP+ljETOJA5g8/riwYRDCDInNapLwmzLpqSzqqXV5iY6VDzSR40iLoh77NJmA6J09aCAFuNhuAk6IWhNGh3K//kTEO4PQ0nTFX38F0qexSE4IkE6fbyjo1QZxCmYw/XAXsBnXPh97UaKBwjt7oiG9UlunNZNX2yBhArC+jLI5XvJMONg72Gp/AVH7DU4MwFjn02tL9f+NLC5udq1hi2+Y=
  email:
    recipients:
      secure: e/BF3lKpqGhPbqXgN5i9tdaVxTJ8jthOpvQeMQb/epC5Abjh/g6FHyQAtlzSW9wzziDdAZX3KXdULsTaxhd1nDKSN5nMIr8z11E+aGHyFfPReMjUUOCXV5kTFG5B8fgCkl5f9I1wv72uTVc6NPCjsl/dBG9pwRjq65y6jMW4a1UqN5UMkbijvpObpwu0g7schrVqSaVhWBcMFOzmXbSxU9yDmoqDZd9KFPLrs3N9fHadPir3h55AX1J3n+S7vxp77w33d17GfYgUrc21D14rkJIZV+DloavxF10zl1iKnvOr2nL7l2JlakQCRSjaOP5qUt1b8NKnyC7ko/cev8kV3Jxj7IKIGfEpftTGUEB+Ck1qQyF7O1Xktgdau7lx4EwLuW3/aBEmzjeRHsA12VQxAArYHJZ7uoYukuGcHE8NaRi/CcrGMjiIWD9f+5sAoXMJnRI5zOcDjdGJ3tyyAbjFXi2Im/FLUDSAeXuKV+8tTWLvDEINRrYhYW1N+ALOTfV+4Lu5xc09bC4Im28iE0IqR+8kOc3Qs8vmUSZxLq6NpsI+IOEsH1IKZW2vRDpacOGukD7/a7dTxii1yRgU/kLv2x30k3pLB6TrHTqO62KlHEF4YQu4pbnRE4LxRv3aCfdkeIMv3FdG8BbjkADZNMdE25nx/c6RBqUOZFpnU5dXaMc=
